project: TwoFAS.xcodeproj
schemes:
- TwoFAS
retain_objc_accessible: true
retain_swift_ui_previews: true
report_exclude:
- "**/*+Generated.swift"
- "**/Generated/**"
- "**/SourcePackages/**"
- "**/*.pb.swift"
